// @deterministic score: 97/100
//   [minor] llm/intent-legibility  The exported symbol `writeSurfaces` suggests coordinating multiple general 'surfaces,' but its functionality is highly specific: it writes to two distinct output files, `DETERMINISTIC.md` and `README.md`. This generic name diminishes clarity about the function's concrete side effects. → Rename `export async function writeSurfaces(...)` to `export async function updateReportAndReadme(...)` to explicitly signal that both primary report output files are managed within this single function call.
// @deterministic:end
import { promises as fs } from "node:fs";
import { score } from "./score.js";
import { repoHealth, worstFile, type RepoIndex } from "./index-store.js";

/**
 * Surfaces the repo score in three layers (issue #73): a one-line README block
 * (the headline + viral wedge), a committed DETERMINISTIC.md dashboard (the
 * report it points to), and the per-file annotations (the detail, already in the
 * files). Footprint is a guest: idempotent, change-only, strippable.
 */

const REPORT_FILE = "DETERMINISTIC.md";
const README_FILE = "README.md";
const RM_START = "<!-- deterministic:start -->";
const RM_END = "<!-- deterministic:end -->";

/** The committed dashboard: score + repo-level issues in full + an index of flagged files. */
export function renderReport(index: RepoIndex, repoScore: number, totalFiles: number): string {
  const flagged = Object.keys(index.problems).sort(
    (a, b) => score(index.problems[a]!).score - score(index.problems[b]!).score,
  );
  const worst = worstFile(index);
  // Headline = worst-file-dominant (v2, #66); health = the count-invariant average,
  // surfaced alongside so breadth stays visible. See ADR-0002.
  const healthNote =
    `_health ${repoHealth(index, totalFiles)}/100 (typical file)` +
    (worst ? ` · weakest file [\`${worst.file}\`](./${worst.file}) ${worst.score}/100_` : "_");
  const lines: string[] = [
    "# Deterministic report",
    "",
    "_Generated by [Deterministic](./README.md) — a linter for AI coding agents. Do not edit by hand._",
    "",
    `**Repo score: ${repoScore}/100**  ·  ${totalFiles} files scored  ·  ${flagged.length} with issues`,
    healthNote,
    "",
    "## Repo-level issues",
    "",
  ];
  if (index.repoIssues.length === 0) lines.push("_None._");
  else for (const i of index.repoIssues) lines.push(`- **[${i.severity}]** \`${i.ruleId}\` — ${i.problem} → ${i.fix}`);
  lines.push("", "## Files with issues", "");
  if (flagged.length === 0) lines.push("_None — every file is clean._");
  else
    for (const path of flagged) {
      const n = index.problems[path]!.length;
      lines.push(`- [\`${path}\`](./${path}) — ${score(index.problems[path]!).score}/100 (${n} issue${n === 1 ? "" : "s"})`);
    }
  return lines.join("\n") + "\n";
}

/** The one restrained README line. */
export function renderReadmeBlock(repoScore: number): string {
  return [
    RM_START,
    `> 🤖 This repo is linted for AI coding agents by **Deterministic** — repo score **${repoScore}/100**. See [DETERMINISTIC.md](./${REPORT_FILE}).`,
    RM_END,
  ].join("\n");
}

/** Remove the README block (for strip-before-score, so the line never scores itself). */
export function stripReadmeBlock(content: string): string {
  const start = content.indexOf(RM_START);
  if (start === -1) return content;
  const end = content.indexOf(RM_END, start);
  if (end === -1) return content;
  const cut = content.slice(0, start) + content.slice(end + RM_END.length);
  return cut.replace(/\n{3,}/g, "\n\n").replace(/\s+$/, "\n");
}

/** Write the file only if its content actually changed (no churn from no-op runs). */
async function writeIfChanged(file: string, content: string): Promise<boolean> {
  let current = "";
  try {
    current = await fs.readFile(file, "utf8");
  } catch {
    /* missing */
  }
  if (current === content) return false;
  await fs.writeFile(file, content, "utf8");
  return true;
}

/** Write DETERMINISTIC.md and update the README one-liner (idempotent, change-only). */
export async function writeSurfaces(index: RepoIndex, repoScore: number, totalFiles: number): Promise<void> {
  await writeIfChanged(REPORT_FILE, renderReport(index, repoScore, totalFiles));

  let readme = "";
  try {
    readme = await fs.readFile(README_FILE, "utf8");
  } catch {
    return; // no README — don't create one
  }
  const block = renderReadmeBlock(repoScore);
  const stripped = stripReadmeBlock(readme);
  const next = stripped.replace(/\n?$/, "\n") + "\n" + block + "\n";
  await writeIfChanged(README_FILE, next);
}
